version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - librsvg2-bin  # For sphinxcontrib.rsvgconverter to convert SVG to PDF
    - texlive-xetex # For xelatex engine
    - texlive-fonts-recommended # Common fonts
    - texlive-fonts-extra     # More fonts, good for unicode
    - texlive-latex-extra     # Additional LaTeX packages, often useful
    - texlive-lang-other     # For non-English language support
    - fonts-noto-cjk         # For CJK characters
    - fonts-noto-color-emoji # For emoji support
    - ghostscript            # For PDF processing
    - latexmk               # For LaTeX compilation
    - fonts-freefont-ttf     # For FreeSerif font

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
