version: '3.8'
services:
  # tradebot:
  #   build: .
  #   container_name: tradebot
  #   depends_on:
  #     - redis
  #   tty: true
  #   stdin_open: true

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '${NEXUS_REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${NEXUS_REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${NEXUS_REDIS_PASSWORD}

  loki:
    image: grafana/loki:3.3.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./yaml-config:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./.log:/var/log
      - ./yaml-config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped
  
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    ports:
      - '${NEXUS_PG_PORT}:5432'
    environment:
      - POSTGRES_USER=${NEXUS_PG_USER}
      - POSTGRES_PASSWORD=${NEXUS_PG_PASSWORD}
      - POSTGRES_DB=${NEXUS_PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  loki-data:
  postgres_data:
